import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { NavbarComponent } from "@/components";

const interFont = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nicolas Sanhueza | Ingeniero Informático",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" data-theme="dark" className="background-animate">
      <body
        className={`${interFont.className} mx-auto w-full gap-10 flex md:w-3/5 relative`}
      >
        <Providers>
          <NavbarComponent />
          {children}
        </Providers>
      </body>
    </html>
  );
}
